import type { Vehicle } from "@/lib/types/vehicle";

// TODO(M2 backend): remover e substituir por query real na tabela `vehicles`.
export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    brand: "Toyota",
    model: "Corolla XEi",
    year: 2022,
    plate: "ABC1D23",
    color: "Prata",
    km: 32000,
    price: 129900,
    costPrice: 108000,
    status: "disponivel",
    photos: [],
  },
  {
    id: "2",
    brand: "Honda",
    model: "HR-V EXL",
    year: 2021,
    plate: "DEF4E56",
    color: "Branco",
    km: 41000,
    price: 119900,
    costPrice: 99500,
    status: "reservado",
    photos: [],
  },
  {
    id: "3",
    brand: "Jeep",
    model: "Compass Longitude",
    year: 2023,
    plate: "GHI7F89",
    color: "Preto",
    km: 12000,
    price: 168900,
    costPrice: 142000,
    status: "disponivel",
    photos: [],
  },
  {
    id: "4",
    brand: "Chevrolet",
    model: "Onix Premier",
    year: 2020,
    plate: "JKL0G12",
    color: "Vermelho",
    km: 58000,
    price: 78900,
    costPrice: 64000,
    status: "vendido",
    photos: [],
  },
];
