import type { Lead } from "@/lib/types/lead";

// TODO(M4 backend): remover e substituir por query real na tabela `leads` (+ `lead_activities`).
export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Bruno Ferreira",
    phone: "(11) 98888-1010",
    email: "bruno.ferreira@example.com",
    origin: "whatsapp",
    vehicleInterest: "Toyota Corolla XEi",
    stage: "novo",
    vendedorName: "Ana Souza",
    visitDate: null,
    createdAt: "2026-10-20T14:20:00Z",
    activities: [
      {
        id: "a1",
        type: "mensagem",
        description: "Lead chegou perguntando sobre o Corolla anunciado no Instagram.",
        date: "2026-10-20T14:20:00Z",
      },
    ],
  },
  {
    id: "2",
    name: "Camila Rocha",
    phone: "(11) 97777-2020",
    email: null,
    origin: "site",
    vehicleInterest: "Jeep Compass Longitude",
    stage: "novo",
    vendedorName: "Carlos Lima",
    visitDate: null,
    createdAt: "2026-10-21T09:05:00Z",
    activities: [],
  },
  {
    id: "3",
    name: "Diego Martins",
    phone: "(11) 96666-3030",
    email: "diego.martins@example.com",
    origin: "whatsapp",
    vehicleInterest: "Honda HR-V EXL",
    stage: "contato_feito",
    vendedorName: "Ana Souza",
    visitDate: null,
    createdAt: "2026-10-15T11:00:00Z",
    activities: [
      {
        id: "a2",
        type: "mensagem",
        description: "Perguntou sobre disponibilidade de cor branca.",
        date: "2026-10-15T11:00:00Z",
      },
      {
        id: "a3",
        type: "ligacao",
        description: "Retornei a ligação, confirmei que temos em estoque.",
        date: "2026-10-16T15:30:00Z",
      },
    ],
  },
  {
    id: "4",
    name: "Elaine Souza",
    phone: "(11) 95555-4040",
    email: "elaine.souza@example.com",
    origin: "indicacao",
    vehicleInterest: "Chevrolet Onix Premier",
    stage: "visita_agendada",
    vendedorName: "Carlos Lima",
    visitDate: "2026-10-28T15:00:00Z",
    createdAt: "2026-10-10T10:00:00Z",
    activities: [
      {
        id: "a4",
        type: "ligacao",
        description: "Indicação de cliente antigo, já negociou preço por telefone.",
        date: "2026-10-11T09:00:00Z",
      },
      {
        id: "a5",
        type: "visita",
        description: "Agendou visita para test-drive.",
        date: "2026-10-18T13:00:00Z",
      },
    ],
  },
  {
    id: "5",
    name: "Fábio Nogueira",
    phone: "(11) 94444-5050",
    email: null,
    origin: "whatsapp",
    vehicleInterest: "Toyota Corolla XEi",
    stage: "visita_agendada",
    vendedorName: "Ana Souza",
    visitDate: "2026-10-25T10:30:00Z",
    createdAt: "2026-10-12T16:00:00Z",
    activities: [
      {
        id: "a6",
        type: "mensagem",
        description: "Confirmou interesse após ver fotos do carro.",
        date: "2026-10-12T16:00:00Z",
      },
    ],
  },
  {
    id: "6",
    name: "Gustavo Prado",
    phone: "(11) 93333-6060",
    email: "gustavo.prado@example.com",
    origin: "site",
    vehicleInterest: "Jeep Compass Longitude",
    stage: "negociacao",
    vendedorName: "Carlos Lima",
    visitDate: null,
    createdAt: "2026-10-05T08:30:00Z",
    activities: [
      {
        id: "a7",
        type: "visita",
        description: "Veio à loja, fez test-drive.",
        date: "2026-10-09T14:00:00Z",
      },
      {
        id: "a8",
        type: "nota",
        description: "Pediu desconto de 5%, aguardando aprovação do gestor.",
        date: "2026-10-19T17:00:00Z",
      },
    ],
  },
  {
    id: "7",
    name: "Helena Castro",
    phone: "(11) 92222-7070",
    email: "helena.castro@example.com",
    origin: "indicacao",
    vehicleInterest: "Honda HR-V EXL",
    stage: "venda_fechada",
    vendedorName: "Ana Souza",
    visitDate: null,
    createdAt: "2026-09-18T10:00:00Z",
    activities: [
      {
        id: "a9",
        type: "visita",
        description: "Fechou negócio na segunda visita.",
        date: "2026-09-22T11:00:00Z",
      },
    ],
  },
  {
    id: "8",
    name: "Igor Almeida",
    phone: "(11) 91111-8080",
    email: null,
    origin: "whatsapp",
    vehicleInterest: "Chevrolet Onix Premier",
    stage: "perdido",
    vendedorName: "Carlos Lima",
    visitDate: null,
    createdAt: "2026-09-25T13:00:00Z",
    activities: [
      {
        id: "a10",
        type: "nota",
        description: "Fechou com outra revenda por preço.",
        date: "2026-10-02T09:00:00Z",
      },
    ],
  },
];
